import { describe, it, expect } from "vitest";
import { render } from "@testing-library/react";
import { Calendar } from "well-rounded-ui";

describe("<Calendar>", () => {
  it("should render correctly", () => {
    const { container } = render(<Calendar month={0} year={2024} data={[]} />);
    expect(container.firstChild).toMatchInlineSnapshot(`
      <div
        class="calendar-wrapper"
      >
        <div
          class="calendar-header"
        >
          <i
            class="mdi mdi-chevron-left pointer"
          />
          <h2>
            January
             
            2024
          </h2>
          <i
            class="mdi mdi-chevron-right pointer"
          />
        </div>
        <div
          class="calendar"
        >
          <div
            class="day-names"
          >
            <div>
              Monday
            </div>
            <div>
              Tuesday
            </div>
            <div>
              Wednesday
            </div>
            <div>
              Thursday
            </div>
            <div>
              Friday
            </div>
          </div>
          <div
            class="day-numbers"
          >
            <div
              class="week"
            >
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  1
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  2
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  3
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  4
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  5
                </p>
              </div>
            </div>
            <div
              class="week"
            >
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  8
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  9
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  10
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  11
                </p>
              </div>
              <div
                class="day active"
              >
                <p
                  class="day-number"
                >
                  12
                </p>
              </div>
            </div>
            <div
              class="week"
            >
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  15
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  16
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  17
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  18
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  19
                </p>
              </div>
            </div>
            <div
              class="week"
            >
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  22
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  23
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  24
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  25
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  26
                </p>
              </div>
            </div>
            <div
              class="week"
            >
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  29
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  30
                </p>
              </div>
              <div
                class="day"
              >
                <p
                  class="day-number"
                >
                  31
                </p>
              </div>
              <div
                class="day disabled"
              >
                <p
                  class="day-number"
                />
              </div>
              <div
                class="day disabled"
              >
                <p
                  class="day-number"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    `);
  });
});
